apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Cloudformation resource 
  title: 'Cloudformation resource creation'
  description: 'Cloudformation resource creation'
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
